### PR TITLE
fix: tillerino !acc <accuracy> query the pp, some windows stuff

### PR DESCRIPTION
**Pull request by Pure-Peace**

### CODE REVIEW

**Comment by RealistikDash** [comment]
Regarding the windows compatibillity for path, you can use / for windows paths in python too. Eg if I do`open("c:/a.txt")` and it will work plus it doesn't require another condition check.

**Comment by Pure-Peace** [comment]
> Regarding the windows compatibillity for path, you can use / for windows paths in python too. Eg if I do`open("c:/a.txt")` and it will work plus it doesn't require another condition check.

Well, it's true. I don't know why I made this change lol

**Comment by simonglob** [comment]
> Regarding the windows compatibillity for path, you can use / for windows paths in python too. Eg if I do`open("c:/a.txt")` and it will work plus it doesn't require another condition check.

man fuck windows

**Comment by Pure-Peace** [comment]
I did run into problems when compiling on windows, and I can work normally after making these modifications (win10, python3.8 and cython 0.29)

**Pull request merged**
